version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=bitcoiners_prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "4000"
      - "3001" # WebSocket port
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bitcoiners_prod
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_prod_data:/data
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  postgres_prod_data:
  redis_prod_data:
