version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - WS_PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    expose:
      - "4000"
      - "3001"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_WS_URL=/ws
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge
