services:
  # Frontend Service
  - type: web
    name: bitcoiners-frontend
    env: docker
    region: singapore
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /
    startCommand: nginx -g 'daemon off;'
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://bitcoiners-backend.onrender.com
      - key: BACKEND_WS_URL
        value: wss://bitcoiners-backend.onrender.com
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com/ws

  # Backend Service
  - type: web
    name: bitcoiners-backend
    env: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    plan: starter
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: WS_PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: []
