services:
  # Backend Service (Docker)
  - type: web
    name: bitcoiners-backend
    env: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString

  # Frontend Service (Docker)
  - type: web
    name: bitcoiners-frontend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: bitcoiners-env
    healthCheckPath: /
    numInstances: 1

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: []

envVarGroups:
  - name: bitcoiners-env
    envVars:
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com/ws
