services:
  # Main Docker Compose Service
  - type: web
    name: bitcoiners
    env: docker
    region: singapore
    dockerCommand: docker-compose -f docker-compose.prod.yml up
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: []
