services:
  # Frontend Web Service
  - type: web
    name: bitcoiners-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: bitcoiners-env
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service
  - type: web
    name: bitcoiners-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString
      - key: TYPEORM_CONNECTION
        value: postgres
      - key: TYPEORM_SYNCHRONIZE
        value: "true"
      - key: TYPEORM_LOGGING
        value: "true"
      - key: TYPEORM_ENTITIES
        value: dist/models/*.js
      - key: TYPEORM_MIGRATIONS
        value: dist/migrations/*.js
      - key: TYPEORM_SUBSCRIBERS
        value: dist/subscribers/*.js

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free

envVarGroups:
  - name: bitcoiners-env
    envVars:
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com
