services:
  # Frontend Web Service
  - type: web
    name: bitcoiners-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          name: bitcoiners-backend
          type: web
          property: url
      - key: VITE_WS_URL
        fromService:
          name: bitcoiners-backend
          type: web
          property: url
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service
  - type: web
    name: bitcoiners-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
