services:
  - type: web
    name: bitcoiners-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com/ws

  - type: web
    name: bitcoiners-backend
    env: node
    region: singapore
    buildCommand: |
      cd backend
      npm ci
      npm run build
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    plan: starter
    autoDeploy: false
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: WS_PORT
        value: 3001
      - key: DATABASE_URL
        value: postgresql://bitcoiners:cuh6gpBTE8kWRk2IVZPTUjEeZ63tCmLk@dpg-ctii6mlds78s73eg1t2g-a.singapore-postgres.render.com/bitcoiners_gxuf
      - key: REDIS_URL
        value: redis://default:password@red-ctii6mlds78s73eg1t20.singapore-redis.render.com:6379

  - type: redis
    name: bitcoiners-redis
    ipAllowList: ["0.0.0.0/0"]
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: ["0.0.0.0/0"]
    region: singapore
