services:
  # Frontend Web Service
  - type: web
    name: bitcoiners-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: bitcoiners-env
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

  # Backend API Service
  - type: web
    name: bitcoiners-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    healthCheckTimeout: 5
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString
      - key: TYPEORM_CONNECTION
        value: postgres
      - key: TYPEORM_SYNCHRONIZE
        value: "true"
      - key: TYPEORM_LOGGING
        value: "true"
      - key: TYPEORM_ENTITIES
        value: dist/models/*.js
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: []

envVarGroups:
  - name: bitcoiners-env
    envVars:
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com
