services:
  # Frontend Service (Static Site)
  - type: web
    name: bitcoiners-frontend
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    dependsOn:
      - bitcoiners-backend
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://bitcoiners-backend.onrender.com/api
      - key: VITE_WS_URL
        value: wss://bitcoiners-backend.onrender.com/ws

  # Backend Service (Node.js)
  - type: web
    name: bitcoiners-backend
    env: node
    region: singapore
    buildCommand: |
      cd backend
      npm ci
      npm run build
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /health
    plan: starter
    dependsOn:
      - bitcoiners-db
      - bitcoiners-redis
    autoDeploy: false # Disable auto-deploy to ensure manual control
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: WS_PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: bitcoiners-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: bitcoiners-redis
          type: redis
          property: connectionString

  # Redis Service
  - type: redis
    name: bitcoiners-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: bitcoiners-db
    databaseName: bitcoiners
    user: bitcoiners
    plan: free
    ipAllowList: []
    region: singapore # Match backend region
    postgresMajorVersion: 15 # Specify PostgreSQL version
