FROM node:18

WORKDIR /app

# Install development dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port 5173 for Vite
EXPOSE 5173

# Command to run development server
CMD ["npm", "run", "dev"]
